from food import Pizza, Ingredient, Decorator

if __name__ == "__main__":
    myPizza = Pizza([10, 15, 20], 'Familiar')
    jamon = Ingredient([1.5, 1.75, 2], 'jamón')
    champinones = Ingredient([1.75, 2.05, 2.5], 'champiñones')
    pimenton = Ingredient([1.5, 1.75, 2], 'pimentón')
    myPizza = Decorator(myPizza, jamon)
    myPizza = Decorator(myPizza, jamon)
    myPizza = Decorator(myPizza, jamon)
    myPizza = Decorator(myPizza, pimenton)
    myPizza = Decorator(myPizza, pimenton)
    myPizza = Decorator(myPizza, pimenton)
    myPizza = Decorator(myPizza, pimenton)
    myPizza = Decorator(myPizza, pimenton)
    myPizza = Decorator(myPizza, champinones)
    myPizza = Decorator(myPizza, champinones)
    print(myPizza.cost())
    print(myPizza.name())
    print(myPizza.recipe())
